---
apiVersion: v1
kind: Namespace
metadata:
  name: animals
  labels:
    client: lion
---
apiVersion: v1
kind: Pod
metadata: 
  name: lion-server
  namespace: animals
  labels:
    client: lion
    app: web-server
spec: 
  containers:
  - name: lion-app
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lion-server-service
  namespace: animals  
spec:
  type: NodePort
  selector:
    app: web-server
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
