---
apiVersion: v1
kind: Namespace
metadata:
  name: animals
  labels:
    client: lion
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-version-1
  namespace: animals
  labels:
    client: lion
spec:
  strategy:
    rollingUpdate:
      maxSurge: 0           #  3 20 30s - 100% 1min down 1000
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 3
  minReadySeconds: 10
  selector:
    matchLabels:
      role: webserver
  template:
    metadata:
      name: web
      labels:
        role: webserver
    spec:
      containers:
      - name: web
        image: nginx
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
