---
apiVersion: v1
kind: Pod
metadata:
  name: terra-web-server
  namespace: terraform  
  labels:
    environment: production
    app: nginx
spec:
  containers:
  - name: terra-web-server
    image: nginx
    ports:
    - containerPort: 80
...



