---
apiVersion: v1
kind: Namespace
metadata:
  name: birds
  labels:
    client: duck
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-servers
  namespace: birds
spec:
  replicas: 2
  minReadySeconds: 10
  selector:
    matchLabels:
      role: web
  template:
    metadata:
      name: web
      labels:
        role: web
        client: duck
    spec:
      containers:
        - name: web
          image: jjino/web-app:v2
          ports:
            - containerPort: 80
        - name: redis-server
          image: redis
          ports:
          - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: lion-server-service
  namespace: birds
  labels:
    client: duck
spec:
  type: NodePort
  selector:
    role: web
  ports:
    - name: http
      port: 80
      nodePort: 30002
    - name: redis
      port: 6379
      nodePort: 30003
