---
apiVersion: v1
kind: Namespace
metadata:
  name: animals
  labels:
    client: lion  

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: lion-server
  namespace: animals  
  labels:
    client: lion
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: web
        image: nginx
        ports:
          - containerPort: 80  
---            
apiVersion: v1
kind: Service
metadata:
  name: duck-server-service
  namespace: animals
  labels:
    client: lion    
spec:
  type: NodePort
  selector:
    app: web-server
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007



        
